export enum AuditAction {
  // Debt
  DEBT_CREATED = 'DEBT_CREATED',
  DEBT_UPDATED = 'DEBT_UPDATED',
  DEBT_STATUS_CHANGED = 'DEBT_STATUS_CHANGED',
  DEBT_CANCELLED = 'DEBT_CANCELLED',

  // Payment
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_ADJUSTMENT = 'PAYMENT_ADJUSTMENT',
  PAYMENT_REVERSAL = 'PAYMENT_REVERSAL',

  // Invitation
  INVITATION_CREATED = 'INVITATION_CREATED',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',

  // Business Users
  BUSINESS_USER_ADDED = 'BUSINESS_USER_ADDED',
  BUSINESS_USER_ROLE_UPDATED = 'BUSINESS_USER_ROLE_UPDATED',
  BUSINESS_USER_REMOVED = 'BUSINESS_USER_REMOVED',

  // Debtor
  DEBTOR_CREATED = 'DEBTOR_CREATED',
  DEBTOR_UPDATED = 'DEBTOR_UPDATED',
  DEBTOR_INACTIVATED = 'DEBTOR_INACTIVATED',

  //business
  BUSINESS_CREATED = 'BUSINESS_CREATED',
  BUSINESS_UPDATED = 'BUSINESS_UPDATED',
  BUSINESS_DEACTIVATED = 'BUSINESS_DEACTIVATED',
}

export interface LogParams {
  userId?: string;
  action: AuditAction;
  entity: string;
  entityId?: string;
  meta?: any;
}
